## SWORD Dino Project Minimal XDC

set_property PACKAGE_PIN AC18 [get_ports clk_100mhz]
set_property IOSTANDARD LVCMOS18 [get_ports clk_100mhz]
create_clock -period 10.000 -name clk_100mhz [get_ports clk_100mhz]

set_property PACKAGE_PIN W13 [get_ports RSTN]
set_property IOSTANDARD LVCMOS18 [get_ports RSTN]

set_property PACKAGE_PIN N21 [get_ports {vga_r[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[0]}]
set_property SLEW FAST [get_ports {vga_r[0]}]
set_property PACKAGE_PIN N22 [get_ports {vga_r[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[1]}]
set_property SLEW FAST [get_ports {vga_r[1]}]
set_property PACKAGE_PIN R21 [get_ports {vga_r[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[2]}]
set_property SLEW FAST [get_ports {vga_r[2]}]
set_property PACKAGE_PIN P21 [get_ports {vga_r[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_r[3]}]
set_property SLEW FAST [get_ports {vga_r[3]}]

set_property PACKAGE_PIN R22 [get_ports {vga_g[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[0]}]
set_property SLEW FAST [get_ports {vga_g[0]}]
set_property PACKAGE_PIN R23 [get_ports {vga_g[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[1]}]
set_property SLEW FAST [get_ports {vga_g[1]}]
set_property PACKAGE_PIN T24 [get_ports {vga_g[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[2]}]
set_property SLEW FAST [get_ports {vga_g[2]}]
set_property PACKAGE_PIN T25 [get_ports {vga_g[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_g[3]}]
set_property SLEW FAST [get_ports {vga_g[3]}]

set_property PACKAGE_PIN T20 [get_ports {vga_b[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[0]}]
set_property SLEW FAST [get_ports {vga_b[0]}]
set_property PACKAGE_PIN R20 [get_ports {vga_b[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[1]}]
set_property SLEW FAST [get_ports {vga_b[1]}]
set_property PACKAGE_PIN T22 [get_ports {vga_b[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[2]}]
set_property SLEW FAST [get_ports {vga_b[2]}]
set_property PACKAGE_PIN T23 [get_ports {vga_b[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {vga_b[3]}]
set_property SLEW FAST [get_ports {vga_b[3]}]

set_property PACKAGE_PIN M22 [get_ports vga_hs]
set_property IOSTANDARD LVCMOS33 [get_ports vga_hs]
set_property SLEW FAST [get_ports vga_hs]
set_property PACKAGE_PIN M21 [get_ports vga_vs]
set_property IOSTANDARD LVCMOS33 [get_ports vga_vs]
set_property SLEW FAST [get_ports vga_vs]

set_property PACKAGE_PIN N18 [get_ports PS2_clk]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_clk]
set_property PACKAGE_PIN M19 [get_ports PS2_data]
set_property IOSTANDARD LVCMOS33 [get_ports PS2_data]

set_property PACKAGE_PIN AF25 [get_ports Buzzer]
set_property IOSTANDARD LVCMOS33 [get_ports Buzzer]
